### ISSUE TITLE
Blocking problem with the latest build (post 0.99.6) on Windows

### ISSUE THREAD

**Issue by max904-github** [line/armeria#2750]
There is a blocking problem with the latest build (post 0.99.6) on Windows.
The `docs-client` was always giving me headaches (yarn frequent timeout errors, yarn proxy issues), but now it just stopped working due to line breaks incompatibility issue.
The build fails on the following command:
```
…\.gradle>nodejs\node-v12.17.0-win-x64\node.exe npm\npm-v6.14.5\node_modules\npm\bin\npm-cli.js run lint
```
For every single file it processes it gives an error for each line, like below:
```
…\armeria\docs-client\.eslintrc.js
  1:62  error  Delete `␍`  prettier/prettier
  2:1   error  Delete `␍`  prettier/prettier
  ...
```
I could only pass it when I manually forced it to "fix" the line breaks with `--fix` option, but that, of course, modified all the processed files.
Please consider a fix for the Windows builds.

There is also one other problem with Windows build. During the build, line breaks always change for the following files:
```
examples/grpc-kotlin/gen-src/main/java/example/armeria/grpc/kotlin/Hello.java
examples/grpc-kotlin/gen-src/main/grpc/example/armeria/grpc/kotlin/HelloServiceGrpc.java
```
This problem existed even before 0.99.6 but was not blocking, although was quite annoying.

**Comment by max904-github** [comment]
A quick workaround for the blocking build issue is to add following lines to `.gitattributes` file, before better solution found for Node/Prettier infrastructure:
```
/docs-client/**/*.js text eol=lf
/docs-client/**/*.ts text eol=lf
/docs-client/**/*.tsx text eol=lf
```
Of course, it does not solve the grpc-kotlin examples problem.

**Comment by trustin** [comment]
Oh, it seems like `prettier` does not respect the operating system's line endings.. Let me send a fix PR soon.

**Comment by trustin** [comment]
@max904-github Could you do a clean checkout of `master` again? I've just pushed a fix.

**Comment by max904-github** [comment]
Everything builds fine now! Thank you!
Still see those two files (`Hello.java` and `HelloServiceGrpc.java`) modified during the build though, plus `web-licenses.txt`.

**Comment by trustin** [comment]
Could you tell us the full path of the `Hello.java` and `HelloServiceGrpc.java` that are modified?

**Comment by max904-github** [comment]
I've provided those in the original issue text:
```
<armeria repo>/examples/grpc-kotlin/gen-src/main/java/example/armeria/grpc/kotlin/Hello.java
<armeria repo>/examples/grpc-kotlin/gen-src/main/grpc/example/armeria/grpc/kotlin/HelloServiceGrpc.java
```

**Comment by trustin** [comment]
Doh! Sorry I missed them out. It seems like some code generators generate code with Windows line ending. I wonder there's an option for enforcing the line ending of the generated files.

**Comment by max904-github** [comment]
These files are part of the code base and I assume those a being "touched" or re-generated as part of the build. If the files are being generated during the build (and `Hello.java` seems to be generated out of `hello.proto`) those should not be part of the code base. For instance, Gradle default generated source location is under `build/generated`...

**Comment by trustin** [comment]
IIUC, the reason why the files related with grpc-kotlin are checked into the repository is because grpc-kotlin generator support on Windows is not as good as that on Linux last time we checked. Does your windows build success even after you delete the two files even if you do not have any tooling (e.g. protoc.exe) in your `PATH` environment variable? /cc @anuraaga

**Comment by anuraaga** [comment]
Actually I noticed too that my build doesn't succeed on Windows lately because it looks like the gRPC kotlin codegen is still happening and failing. Can we disable it?

**Comment by ikhoon** [comment]
> Actually I noticed too that my build doesn't succeed on Windows lately because it looks like the gRPC kotlin codegen is still happening and failing. Can we disable it?

https://github.com/grpc/grpc-kotlin/issues/116 gRPC-Kotlin compiler still has a problem on Windows.
However, the Window builds in AppVeyor CI finish successfully because we checked in the generated code.

**Comment by anuraaga** [comment]
Ah oops, I just noticed (since it failed...) the build that's failing now for me is `grpc-reactor:generateProto` since it requires `java` on the path. Can we check that in too?

Not sure why the kotlin files would get touched if that's disabled.

**Comment by trustin** [comment]
I ran the build by myself on Windows and no files are modified during the build process. 🤔

**Comment by trustin** [comment]
> Ah oops, I just noticed (since it failed...) the build that's failing now for me is `grpc-reactor:generateProto` since it requires `java` on the path

How about contacting the reactive-grpc devs, so that they fix the problem? /cc @cbornet

**Comment by cbornet** [comment]
You shouldn't have the gRPC reactor plugin in the grpc-kotlin example. Something must be wrong with the updating script.

**Comment by trustin** [comment]
@cbornet Sorry that the title of this issue is misleading. What @anuraaga said is that the gRPC reactor plugin fails when `java` is not in `PATH`, i.e. It not related with Kotlin. The failing module `:examples:grpc-reactor` does not have Kotlin dependency.

**Comment by cbornet** [comment]
reactive-grpc now uses [canteen](https://github.com/salesforce/grpc-java-contrib/blob/master/canteen/README.md#how-does-canteen-work) to package an executable jar. From the docs, it seems that Java is indeed required on the path for windows. Maybe @rmichela can help ?

**Comment by rmichela** [comment]
Reactive-gRPC has used canteen for gradle builds since 1.0.0. The gradle-protobuf-plugin expects that all protoc plugins are packaged as native executables. It cannot link to a java class natively like the maven-protobuf-plugin. Canteen adds a native executable stub to the reactive-gRPC code generator jar that executes the necessary `java -jar` command for gradle. This command uses the path to locate the java executable, as if the user had executed the command themself. 

Why is java not on the user’s path? Can it be added?

**Comment by rmichela** [comment]
For additional context, protobuf-maven-plugin shells out to [WinRunner4J](http://winrun4j.sourceforge.net/) when executing Java plugins on Windows.

**Comment by anuraaga** [comment]
Don't think it can be added IMO. Build tools for general use should strive for the principal of reproducibility - depending on environment variables like PATH makes that impossible. 

I know grpc-kotlin has a worse problem of depending on bash. I can't remember if reactor does too or if it's just the path problem.

Both should either use go to write the plugin or look at graal. Worst case is making sure to publish something that can work in bash and cmd, respecting java_home and path. This is the gradlew / mvnw strategy and is fine too - but in 2020 seems harder than cross compiling to native!

**Comment by rmichela** [comment]
Does your build environment at least have `java-home` set?

**Comment by anuraaga** [comment]
The JAVA_HOME environment is set and used by Gradle. gradlew has some more magic related to the Java environment too FWIU. Replicating that in a protoc plugin would be ok too, but it should make sure to work on both bash and cmd at the least to be cross platform similar to Gradle. That tends to be the hard part for non-native scripts.
